/* Subsequences of String
You are given a string 'STR' containing lowercase English letters from a to z inclusive. 
Your task is to find all non-empty possible subsequences of 'STR'.

A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order.
https://www.naukri.com/code360/problems/subsequences-of-string_985087*/
#include<iostream>
#include<vector>
using namespace std;

void solve(string str,string output,int index,vector<string>& ans){
    //base case-push all the outputs in answer vector
    if(index>=str.length()){
        ans.push_back(output);
        return;
    }

    //recusivly call by excluding current element
    solve(str,output,index+1,ans);
    
    //push the element
    output.push_back(str[index]);

    //recursivly call by including current element
    solve(str,output,index+1,ans);
}

vector<string> subsequence(string str){

    //store the complete answer
    vector<string> ans;

    //store the partial answer
    string output="";

    //pointer
    int index=0;
    solve(str,output,index,ans);
    return ans;
}

int main() {
    string str = "abc"; 
    vector<string> result = subsequence(str);
    for (const auto& subset : result) {
        cout << "[ ";
        for (const auto& ch : subset) {
            cout << ch << " ";
        }
        cout << "]" ;
    }
    return 0;
}